name: NPM Publish

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: |
            **/node_modules
            ./npm
          key: npm-${{ hashFiles('package-lock.json') }}
          restore-keys: npm
      - name: Install dependencies
        run: npm install
      - run: npm run build:ci
      - uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: dist/xplorecomponents/package.json